### ISSUE TITLE
Versioned node_modules

### ISSUE THREAD

**Issue by IOAyman** [ilyeSudo/1_project_7#1]
Why would you track `node_modules`?   Looking for headaches mathalan :P

**Comment by ilyeSudo** [comment]
Damn! I ain't got a clue what the heck it's doing there! fortunately, we got the headache's pill lol, `npm i`

**Comment by IOAyman** [comment]
Yeah keep sticking to them pill and you'll be next Linkin Park, a drug addict 😛 LOL

Happy coding 😄

**Comment by ilyeSudo** [comment]
Lool! Thanks bruh 😄😄
Happy Coding <3
